export const glimpseConfig = [
  {
    id: "1",
    content: "500 HACKERS",
    content2: "10 PARTNERS",
    src1: "/images/glimpse/pic1.webp",
    src1Blur:"/images/glimpse/glimpseMini/pic1.webp",
    src2: "/images/glimpse/pic6 (1).webp",
    src2Blur:"/images/glimpse/glimpseMini/pic61.webp",
    src3: "/images/glimpse/pic13 (1).webp",
    src3Blur:"/images/glimpse/glimpseMini/pic131.webp",
  },
  {
    id: "2",
    content: "100 PROJECTS",
    content2: "36 HACK HOURS",
    src1: "/images/glimpse/pic3 (1).webp",
    src1Blur : "/images/glimpse/glimpseMini/pic31.webp",
    src2: "/images/glimpse/pic5 (1).webp",
    src2Blur : "/images/glimpse/glimpseMini/pic51.webp",
    src3: "/images/glimpse/pic11 (1).webp",
    src3Blur : "/images/glimpse/glimpseMini/pic111.webp",
    className: "row-reverse",
  },
];